version: '3'
services:
  mysql-master:
    image: mysql-master:v1
    container_name: mysql-master
    environment:
      - MYSQL_ROOT_PASSWORD:root
      - MYSQL_DATABASE:wtdb
    ports:
      - "3307:3306"
    # volumes:
    #   - C:/mysql/master:/var/lib/mysql