CREATE USER 'repluser'@'%' IDENTIFIED BY 'repluser';
GRANT ALTER, CREATE, CREATE ROUTINE, CREATE TABLESPACE, DELETE, CREATE VIEW, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, SELECT, SHOW VIEW, SHOW DATABASES, REPLICATION SLAVE, EXECUTE, PROCESS  ON *.* TO 'repluser'@'%';
FLUSH PRIVILEGES;